# Generated by Django 5.2.8 on 2026-06-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogues/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('nom_fr', models.CharField(blank=True, max_length=255)),
                ('nom_ar', models.CharField(blank=True, max_length=255)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_avant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remise', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='extraction.catalogueimage')),
            ],
        ),
    ]
