# Generated by Django 5.2.8 on 2026-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='product',
            name='crop_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom_ar',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='nom_fr',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix_avant',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='remise',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
