# Generated by Django 5.2.8 on 2026-06-17 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_remove_product_bbox_remove_product_crop_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_traitement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='enseigne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
