# Generated by Django 5.2.8 on 2026-06-17 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0003_product_date_debut_product_date_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseigne', models.CharField(choices=[('MG', 'MG'), ('Carrefour', 'Carrefour'), ('Carrefour Market', 'Carrefour Market'), ('Carrefour Express', 'Carrefour Express'), ('Aziza', 'Aziza'), ('Anouar', 'Anouar'), ('Géant', 'Géant'), ('Monoprix', 'Monoprix'), ('autre', 'Autre')], max_length=100)),
                ('enseigne_autre', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalogues/')),
            ],
        ),
        migrations.DeleteModel(
            name='CatalogueImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_traitement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='enseigne',
        ),
        migrations.AddField(
            model_name='product',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='extraction.catalogueupload'),
        ),
    ]
